In [1]:
import numpy as np

# Creating numpy arrays from python lists

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a1 = np.array([1,2,3,4])

In [5]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([[1,2,3],
               [4,5,6]]) # numpy.ndarray là một kiểu dữ liệu cụ thể trong thư viện NumPy. Nó là một lớp đối tượng trong 
                         #NumPy được sử dụng để biểu diễn mảng nhiều chiều. Mảng NumPy (numpy.ndarray

In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.shape # trả về mảng có bn cột và dòng, có 2 dòng 3 cột


(2, 3)

In [11]:
a2.ndim # ndim là một thuộc tính của đối tượng numpy.ndarray và được sử dụng để lấy số chiều của mảng.

2

In [12]:
a2.dtype # dtype (data type) là một thuộc tính của đối tượng numpy.ndarray và được sử dụng để lấy kiểu dữ liệu của các phần tử trong mảng.

dtype('int32')

In [13]:
a2.size #  được sử dụng để lấy kích thước tổng cộng của mảng, tức là số lượng phần tử trong mảng.

6

# Creating numpy arrays from scratch

### zeros, ones, full, arange, linspace

In [14]:
np.zeros([2,4]) # tạo ra một mảng NumPy với tất cả các phần tử được khởi tạo là số 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros([2,4], dtype = int) 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
np.ones((3,5), dtype = float) # tạo ra một mảng chứa các phần tử có giá trị 1.0. Tuy nhiên, khi in kết quả, các số thực có thể được hiển thị mà không hiển thị phần thập phân không cần thiết.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.arange(0,20, 2) #  chạy từ 0 - 20 (ko bao gồm 20) khoảng cách là 2 giữa các phần tử

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
np.full((3,5), 6.9) #  tham số đầu tiên của hàm np.full() là shape, là một tuple hoặc list chứa kích thước của mảng đầu ra mà bạn muốn tạo.

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

In [6]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0,1, 5)  # được sử dụng để tạo ra một mảng các giá trị có giá trị đều nhau trong một khoảng giá trị cho trước.
                     #  tạo một mảng 1D chứa 5 phần tử, bắt đầu từ 0 và kết thúc bởi 1, với các phần tử được phân bố đều trong khoảng đó.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Random


In [7]:
np.random.random((4,4))

array([[0.29033747, 0.95266667, 0.3611485 , 0.43064237],
       [0.50198506, 0.04270224, 0.88194937, 0.67499838],
       [0.86297237, 0.09424136, 0.51586024, 0.03862805],
       [0.18928065, 0.29877569, 0.59106398, 0.51710711]])

In [15]:
np.random.rand(4,4) # tương tự như random nhưng không cần shape() mà truyền trực tiếp luôn

array([[0.99529957, 0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232, 0.31720174],
       [0.77834548, 0.94957105, 0.66252687, 0.01357164],
       [0.6228461 , 0.67365963, 0.971945  , 0.87819347]])

In [5]:
# seed for reproducibility
np.random.seed(0)  # cho phép ta khởi tạo một chuỗi số ngẫu nhiên tương tự nhau mỗi lần thực thi chương trình.
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [13]:
np.random.normal(0,1, (3,3)) # tạo ra một mảng 2D có kích thước (3, 3) với các giá trị được rút ra từ phân phối chuẩn (normal distribution) có trung bình 0 và độ lệch chuẩn 1.

array([[-0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252]])

In [14]:
np.random.randint(0,10, (4,5))

array([[8, 1, 1, 7, 9],
       [9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4],
       [4, 6, 4, 4, 3]])

## Array Indexing & Slicing


## one-dimensional subarray

In [4]:
x1 = np.random.randint(20, size = 6)

In [7]:
x1

array([10,  6,  5, 11,  4, 19])

In [10]:
x1[4], x1[0], x1[-1]  #return theo vị trí (-1) là vị trí cuối cùng

(4, 10, 19)

## Multi - dimensional array

In [13]:
x2 = np.random.randint(10, size = (3,4))

In [14]:
x2

array([[7, 0, 1, 9],
       [9, 0, 4, 7],
       [3, 2, 7, 2]])

In [15]:
x2[1,2] # truy cập và trả về giá trị của phần tử tại vị trí hàng thứ 1 và cột thứ 2 
        #  Lưu ý rằng chỉ số hàng và cột trong Python được bắt đầu từ 0.

4

In [16]:
x2[1,2] = 6  # cập nhật hàng 1 cột 2 thành số 6

In [17]:
x2

array([[7, 0, 1, 9],
       [9, 0, 6, 7],
       [3, 2, 7, 2]])

## Slicing
## x[start : stop : step]

In [16]:
x1

array([10,  6,  5, 11,  4, 19])

In [18]:
x1[0:3]   # "slicing" là một cách để truy cập và chọn một phần của mảng (array) một chiều hoặc nhiều chiều bằng cách sử dụng các chỉ số (index) và các khoảng giá trị (range).

array([10,  6,  5])

In [19]:
# mỗi 2 step
x1[::2]

array([10,  5,  4])

In [20]:
# two rows, three columns
x2[:2,:3]

array([[8, 6, 0],
       [6, 7, 6]])

In [21]:
x2

array([[8, 6, 0, 7],
       [6, 7, 6, 4],
       [7, 8, 5, 5]])

In [22]:
x2[:, :2]

array([[8, 6],
       [6, 7],
       [7, 8]])

## Reshaping of Array & Transpose

In [24]:
grid = np.arange(1,10)
grid.shape  #có thể kiểm tra kích thước của mảng bằng cách sử dụng thuộc tính shape, 

(9,)

In [25]:
grid.reshape((3,3)) # hàm reshape được sử dụng để thay đổi kích thước của một
                     #mảng (array) thành một hình dạng (shape) khác mà vẫn giữ nguyên số phần tử của mảng ban đầu. 
                 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
x=np.array([1,2,3])

In [27]:
x.shape  # 3 dòng 1 cột

(3,)

In [29]:
x.reshape((1,3)).shape  

(1, 3)

In [31]:
x = np.array([[1.,2.], [3.,4.]])

In [32]:
x

array([[1., 2.],
       [3., 4.]])

In [33]:
x.T # Transpose: chuyển cột thành hàng, hàng thành cột

array([[1., 3.],
       [2., 4.]])

## Array concatenation and splitting

In [34]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [35]:
np.concatenate((x,y))  #hàm concatenate được sử dụng để nối các mảng (array) 

array([1, 2, 3, 3, 2, 1])

In [36]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [37]:
np.concatenate((grid, grid)) #axis = 0 by default

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                [6,5,4]])

In [42]:
np.vstack((x, grid))   # sử dụng để sắp xếp các mảng theo chiều dọc. Nó nối các mảng đã cho theo chiều dọc, tạo ra một mảng mới.

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [43]:
# Horizontally stack the arrays: hstack
y = np.array([[99],
             [99]])
np.hstack((y, grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## splitting of arrays

In [45]:
x = np.array([1,2,3,99,69,3,2,1])

In [48]:
x1, x2, x3 = np.split(x, [3,5])  # hàm np.split()trong NumPy được sử dụng để phân tách một mảng thành các phần tử con (mảng con).

In [49]:
x1

array([1, 2, 3])

In [50]:
x2

array([99, 69])

In [51]:
x3

array([3, 2, 1])

## Broadcasting and vectorized operations

In [2]:
a = np.arange(3)  # được sử dụng để tạo mảng 1 chiều với các giá trị từ một giá trị bắt đầu cho một giá trị kết thúc với một bước nhảy cố định.

In [3]:
a

array([0, 1, 2])

In [4]:
a + 5 #Broadcasting  Broadcasting là một tính năng trong NumPy (một thư viện phổ biến cho tính toán số học trong Python) cho phép thực hiện các phép toán trên các mảng có hình dạng khác nhau mà không cần phải thực hiện sao chép dữ liệu.

array([5, 6, 7])

In [5]:
b =np.ones((3,3))

In [6]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
a.shape, b.shape

((3,), (3, 3))

In [9]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [10]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [11]:
c = np.arange(3).reshape((3,1)) # Toán tử reshape trong NumPy được sử dụng để thay đổi hình dạng của một mảng mà không thay đổi dữ liệu trong mảng đó.

In [12]:
c

array([[0],
       [1],
       [2]])

In [13]:
a+c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating & Comparing Arrays


 
 ###  Aggregation

Aggregation = performkng the same operation on a number of things 

In [3]:
list_number = [1,2,3]

In [4]:
ll = np.array(list_number)

In [5]:
ll

array([1, 2, 3])

In [6]:
sum(ll) #python sum()

6

In [7]:
np.sum(ll) #Numpy sum()

6

In [8]:
# Create a massive Numpy array
massive_array = np.random.random(10000)
massive_array[:5]  # trả về 5 phần tử đầu tiên của mảng massive_array
massive_array.shape

(10000,)

In [10]:
%timeit sum(massive_array) # Câu lệnh %timeitlà một câu lệnh trong Jupyter Notebook và IPython có chức năng đo thời gian thực thi của một dòng mã hoặc một đoạn mã.
%timeit np.sum(massive_array) # Numpy is np.sum()

881 µs ± 7.18 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.6 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
np.mean(massive_array) # tính giá trị trung bình của các phần tử trong mass_array

0.49920729958348065

In [12]:
np.max(massive_array)

0.999878911477773